export { LinealChart } from './charts/lineal-chart.component'
export { Avatar } from './common/avatar.component'
export { Header } from './common/header.component'
export { BottomNavigation } from './common/bottom-navigation.component'
export { Button } from './common/button.component'