export { AppRoutes } from './app-router'
export { AuthNavigator } from './auth.navigator'
export { AppNavigator } from './app.navigator'
export { HomeNavigator } from './home.navigator'
export { ProfileNavigator } from './profile.navigator'
export { StatisticNavigator } from './statistic.navigator'
export { StudentNavigator } from './student.navigator'